# See also https://en.wiki.bluespice.com/w/nsfr_img_auth.php/b/b4/Chatbot_Architektur-Channels_and_Secrets_01.svg
secrets:

  # `bluespice/wiki` generic secrets
  INTERNAL_WIKI_SECRETKEY:
    file: /data/.secrets/INTERNAL_WIKI_SECRETKEY
  INTERNAL_WIKI_UPGRADEKEY:
    file: /data/.secrets/INTERNAL_WIKI_UPGRADEKEY

  # `bluespice/wiki` SimpleSAMLphp secrets
  INTERNAL_SIMPLESAMLPHP_ADMIN_PASS:
    file: /data/.secrets/INTERNAL_SIMPLESAMLPHP_ADMIN_PASS
  INTERNAL_SIMPLESAMLPHP_SECRET_SALT:
    file: /data/.secrets/INTERNAL_SIMPLESAMLPHP_SECRET_SALT

  # Connection `bluespice/wiki` <> `bluespice/chat`
  CHAT_BRIDGE_TOKEN:
    file: /data/.secrets/INTERNAL_CHAT_TOKEN
  INTERNAL_CHAT_TOKEN:
    file: /data/.secrets/INTERNAL_CHAT_TOKEN

  CHAT_WIKI_ACCESS_TOKEN:
    file: /data/.secrets/INTERNAL_CHAT_WIKI_ACCESS_TOKEN
  INTERNAL_CHAT_WIKI_ACCESS_TOKEN:
    file: /data/.secrets/INTERNAL_CHAT_WIKI_ACCESS_TOKEN

  # Connection `bluespice/wiki` <> `bluespice/wire`
  #        and `bluespice/wiki` <> `bluespice/chat`
  CHAT_WIKI_CHAT_TOKEN_SALT:
    file: /data/.secrets/INTERNAL_WIKI_TOKEN_AUTH_SALT
  WIRE_TOKEN_SALT:
    file: /data/.secrets/INTERNAL_WIKI_TOKEN_AUTH_SALT
  INTERNAL_WIKI_TOKEN_AUTH_SALT:
    file: /data/.secrets/INTERNAL_WIKI_TOKEN_AUTH_SALT

  WIRE_API_KEY:
    file: /data/.secrets/INTERNAL_WIRE_API_KEY
  INTERNAL_WIRE_API_KEY:
    file: /data/.secrets/INTERNAL_WIRE_API_KEY

  # Connection `bluespice/chat` <> `bluespice/ai`
  AI__SECURITY__STATIC_API_TOKEN:
    file: /data/.secrets/CHAT_AI_CHAT_SERVICE_API_KEY
  CHAT_AI_CHAT_SERVICE_API_KEY:
    file: /data/.secrets/CHAT_AI_CHAT_SERVICE_API_KEY