services:
  cloudflare-tunnel:
    image: cloudflare/cloudflared:latest
    container_name: bluespice-cloudflare-tunnel
    restart: unless-stopped
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - proxy
  proxy:
    environment:
      - HTTPS_METHOD=noredirect
