x-common-environment: &common-environment

services:
  restore:
    image: docker.bluespice.com/bluespice-qa/backup:latest 
    depends_on:
      database:
        condition: service_healthy
    container_name: ${COMPOSE_PROJECT_NAME:-bluespice}-restore
    volumes:
      - ${DATADIR}:/data
      - ${BACKUPDIR}:/data/backup
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    restart: unless-stopped
    command: ["run-backups"]
