secrets:
  INTERNAL_CHAT_TOKEN:
    file: /data/.secrets/INTERNAL_CHAT_TOKEN
  INTERNAL_CHAT_WIKI_ACCESS_TOKEN:
    file: /data/.secrets/INTERNAL_CHAT_WIKI_ACCESS_TOKEN
  INTERNAL_SIMPLESAMLPHP_ADMIN_PASS:
    file: /data/.secrets/INTERNAL_SIMPLESAMLPHP_ADMIN_PASS
  INTERNAL_SIMPLESAMLPHP_SECRET_SALT:
    file: /data/.secrets/INTERNAL_SIMPLESAMLPHP_SECRET_SALT
  INTERNAL_WIKI_UPGRADEKEY:
    file: /data/.secrets/INTERNAL_WIKI_UPGRADEKEY
  INTERNAL_WIKI_SECRETKEY:
    file: /data/.secrets/INTERNAL_WIKI_SECRETKEY
  INTERNAL_WIKI_TOKEN_AUTH_SALT:
    file: /data/.secrets/INTERNAL_WIKI_TOKEN_AUTH_SALT
  INTERNAL_WIRE_API_KEY:
    file: /data/.secrets/INTERNAL_WIRE_API_KEY